### ISSUE TITLE
Get the message index when decrypting with InboundGroupSession

### ISSUE THREAD

**Issue by Zil0** [poljar/python-olm#2]
olm_group_decrypt sets a message_index variable, and this value is needed when checking for replay attacks, see https://matrix.org/docs/guides/e2e_implementation.html#id35.

If I'm not missing anything this value is currently ignored in those bindings.

For the record, here is the relevant line in the upstream bindings: https://git.matrix.org/git/olm/tree/python/olm/inbound_group_session.py#n122.

**Comment by poljar** [comment]
Great catch. Thanks.

**Comment by Zil0** [comment]
Thanks for the quick fix!

**Comment by Zil0** [comment]
Mmmh, maybe it was a bit to quick :)
```
>>> outbound = OutboundGroupSession()
>>> inbound = InboundGroupSession(outbound.session_key)
>>> inbound.decrypt(outbound.encrypt("Test"))
('Test', <cdata 'uint32_t *' owning 4 bytes>)
```

Your tests pass because:
```
>>> "Test", 0 == inbound.decrypt(outbound.encrypt("Test"))
('Test', False)
```

Fun bug!

**Comment by poljar** [comment]
Sorry for that, i forgot that the variable is a pointer.
