### ISSUE TITLE
Building on OpenBSD

### ISSUE THREAD

**Issue by tommyskg** [poljar/python-olm#6]
Hello,

I tried to build this on OpenBSD 6.4 with python2.7, which results in:

    cc -pthread -fno-strict-aliasing -OPT:Olimit=0 -O2 -pipe -DNDEBUG -O2 -pipe -fPIC -fPIC -I/usr/local/include/python2.7 -c build/temp.openbsd-6.4-amd64-2.7/_libolm.c -o     build/temp.openbsd-6.4-amd64-2.7/build/temp.openbsd-6.4-amd64-2.7/_libolm.o
    build/temp.openbsd-6.4-amd64-2.7/_libolm.c:493:18: fatal error: 
      'olm/olm.h' file not found
        #include <olm/olm.h>

I can work around it by setting the include to an absolute path and doing something like the following - but it still seems to result in error when attempting to load the .so in Weechat.

    ffibuilder.set_source(
    "_libolm",
    r"""
        #include "include/olm/olm.h"
        #include "include/olm/inbound_group_session.h"
        #include "include/olm/outbound_group_session.h"
        #include "include/olm/pk.h"
    """, extra_compile_args=["-lolm"])

It also doesn't have the group session header files. Is that how it is supposed to be?

Thanks!

**Comment by poljar** [comment]
Did you install the Olm C library from [here](https://git.matrix.org/git/olm/refs/)? 

The C library is required to build and run the bindings.

**Comment by tommyskg** [comment]
That was part of the issue at least. In addition this ended up as a working solution:

    ffibuilder.set_source(
    "_libolm",
    r"""
        #include <olm/olm.h>
        #include <olm/inbound_group_session.h>
        #include <olm/outbound_group_session.h>
        #include <olm/pk.h>
    """, extra_compile_args=["-I/usr/local/include", "-lolm"])

**Comment by poljar** [comment]
Right, the -I path depends on where you installed the C header and does the compiler already look into that dir. 

I guess the OpenBSD one doesn't look there and Olm installs by default there.
We could probably add this since it would not hurt in any way.

**Comment by tommyskg** [comment]
Yup - I've seen it proposed in other projects as well. In no way an expert on building such libs, so may be something specific to my env as well.

**Comment by tommyskg** [comment]
So, one step closer - but not yet there.

Ran the commands you mentioned and it errors out like predicted:

    >>> import olm
    >>> alice = olm.Account()
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python2.7/site-packages/python_olm-3.0.0-py2.7-openbsd-6.4-amd64.egg/olm/account.py", line 63, in __new__
        obj._buf = ffi.new("char[]", lib.olm_account_size())
    AttributeError: cffi library '_libolm' has no function, constant or global variable named 'olm_account_size'
     >>> alice.identity_keys
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    NameError: name 'alice' is not defined

However, I did a fresh clone, and it imported and ran all three above commands fine.

**Comment by tommyskg** [comment]
I'm closing this myself. Learned a lot, and hopefully contributed something to future docs.

**Comment by poljar** [comment]
Could you describe what the problem and solution was? Just for potential OpenBSD users that might stumble upon the same issue?

**Comment by tommyskg** [comment]
Sure thing.

Problem was compiler cross-platform args. I ended up with something like the code snippet I mentioned earlier:

    ffibuilder.set_source(
    "_libolm",
    r"""
        #include <olm/olm.h>
        #include <olm/inbound_group_session.h>
        #include <olm/outbound_group_session.h>
        #include <olm/pk.h>
    """, libraries=["olm"],extra_compile_args=["-I/usr/local/include"])

Other than that it compiled fine as is.

As a side-note I think my other issue was that I changed something unintentionally. After a fresh clone it worked fine with the changes above.
