### ISSUE TITLE
Olm README does not know about this project

### ISSUE THREAD

**Issue by almereyda** [poljar/python-olm#7]
In https://git.matrix.org/git/olm/tree/README.rst one is suggested to install `python-olm` through the `python` directory in that git tree.

Since it appears this module here is more up to date, one could update the reference there to point at this repository here, too.

**Comment by poljar** [comment]
Everything that is here is already posted to be merged in the matrix.org repo. Once this is done and the module on matrix.org is installable via pip this repo will be archived. So no point in mentioning this repo over there.
